### ISSUE TITLE
代码执行异常

### ISSUE THREAD

**Issue by Ziven-n** [InsightopTech/cloudbase_ce#8]
<img width="775" alt="截屏2023-12-04 11 45 43" src="https://github.com/InsightopTech/cloudbase_ce/assets/15608631/0f95dd63-981a-4af5-9743-a62418a38622">

**Comment by bookshiyi** [comment]
嗨，感谢你的反馈。

在我的测试中目前没有出现这个问题，请尝试检查一下你的env id是否已经设置正确。
另外可参考cloudbase官方的开发文档。

欢迎随时讨论

**Comment by bookshiyi** [comment]
@Ziven-n 哈喽，还有没收到你的反馈，不知道你的问题是否已经解决。
我先将issue关闭，如果有问题欢迎继续讨论

**Comment by Ziven-n** [comment]
<img width="181" alt="截屏2023-12-06 09 38 53" src="https://github.com/InsightopTech/cloudbase_ce/assets/15608631/ad7c9442-2b47-4889-abd6-88a9b0a08e8a">
是有配置的

**Comment by bookshiyi** [comment]
> <img alt="截屏2023-12-06 09 38 53" width="181" src="https://private-user-images.githubusercontent.com/15608631/288254135-ad7c9442-2b47-4889-abd6-88a9b0a08e8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NDM4MjgsIm5iZiI6MTcwMTg0MzUyOCwicGF0aCI6Ii8xNTYwODYzMS8yODgyNTQxMzUtYWQ3Yzk0NDItMmI0Ny00ODg5LWFiZDYtODhhOWIwYTA4ZThhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDA2MTg0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhZjc0ODAzMDA0MzJkZTNiYWY1ODNjZDAzNTMwZGRlOTczZmM4NjVmOTgyOTQzZDE4NWE0MjcwMzlkODFlY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NOaLJOkaYHbxu8WseDj6GW63qb136MVvj1ASwgbKUFk"> 是有配置的

建议重点核对一下图片中的env, appAccess/key, appAccess/version 是否和cloudbase控制台的设置一致
以及app的identifier是否一致，类似：com.hostname.example

**Comment by bookshiyi** [comment]
哈喽@Ziven-n ，你的问题已经解决了吗？
